coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 1%
    patch:
      default:
        target: 70%

ignore:
  - "bundled/**/*"
  - "cmd/**/*"
  - "internal/install/**/*"
  - "internal/testutil/**/*"
  - "*_test.go"
